name: DevOps CI Pipeline

on:
  push:
    branches:
      - main
      - ash-assignment
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Backend Setup
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Backend Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r dependencies.txt

      - name: Run Django Check
        run: |
          cd backend
          python manage.py check
        env:
          DJANGO_SECRET_KEY: ${{ secret.DJANGO_SECRET_KEY }}      #This passes the secret into CI environment

      # Frontend Setup
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # Docker Build
      - name: Build Docker Images
        run: |
          docker build -t backend-image ./backend
          docker build -t frontend-image ./frontend

